# 100 Numpy Exercises

### Note: Credits of this work goes to rougier, you may check the original notebook here: https://github.com/rougier/numpy-100

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name np (★☆☆)


In [1]:
import numpy as np
print('Package imported successfully!')

Package imported successfully!


#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
np.__version__

'1.21.1'

In [9]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)


In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [117]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python.py'` not found.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [12]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [13]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [17]:
Z = np.arange(10)
print(Z)
Z = Z[::-1]
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [18]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [23]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)


In [26]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)


In [27]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.83488377 0.33425946 0.54223651]
  [0.24521599 0.82734952 0.97223068]
  [0.17332459 0.26574845 0.74007175]]

 [[0.35055623 0.18894543 0.90911098]
  [0.59597984 0.36480038 0.18960965]
  [0.64286908 0.58160448 0.23554194]]

 [[0.0874947  0.24062318 0.01278039]
  [0.26226828 0.04602483 0.42884015]
  [0.77052864 0.85339648 0.52156729]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [192]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print('The minimum value: ' + str(Zmin))
print('The maximum value: ' + str(Zmax))

print('--------------')

#To print them together:
print(Zmin, Zmax)

The minimum value: 0.01676469013394133
The maximum value: 0.994205866476089
--------------
0.01676469013394133 0.994205866476089


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [63]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5143733880898366


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [70]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [189]:
print('First way:')
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
print('\nSecond way:')
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

First way:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Second way:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [81]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [84]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [87]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [116]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [91]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)


In [96]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.43467086  0.68648241  1.33634862 -0.7059114  -0.82181736]
 [ 0.05124579  1.17047876  0.87503171 -0.41902593 -0.83515555]
 [ 0.64263326  1.55664507  0.66007972  1.23655368  1.22228899]
 [-0.54617966  1.17183323 -0.81893575 -1.45072918 -1.29404833]
 [-1.84711926 -0.96643693 -1.07154326 -0.07147436  0.67342658]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [98]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [188]:
print('First way:')
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
print('\nSecond way:')
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

First way:
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

Second way:
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [114]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)


print(sum(range(5),-1))

In [113]:
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

Z<Z>Z

In [128]:
Z = 5

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

3125
16
False
5j
5.0
False


#### 28. What are the result of the following expressions? (★☆☆)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)

In [134]:
np.seterr(divide='ignore', invalid='ignore') # To ignore diving by zero error
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)


In [187]:
print('First way:')
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print('\nSecond way:')
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

First way:
[-6. -3.  4.  1. -7.  3.  3.  9. -4.  6.]

Second way:
[-6. -3.  4.  1. -7.  3.  3.  9. -4.  6.]


#### 30. How to find common values between two arrays? (★☆☆)


In [146]:
Z1 = np.random.randint(0,10,5)
Z2 = np.random.randint(0,10,5)
print(Z1, Z2)
print(np.intersect1d(Z1,Z2))

[1 3 6 6 4] [4 1 7 1 9]
[1 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [149]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0
    
print('All warnings are ignored!')    

All warnings are ignored!


#### 32. Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)


In [150]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [2]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print('Yesterday: ' + str(yesterday))
print('Today: ' + str(today))
print('Tomorrow: ' + str(tomorrow))

Yesterday: 2021-08-22
Today: 2021-08-23
Tomorrow: 2021-08-24


#### 34. How to get all the dates corresponding to the month of July 2021? (★★☆)


In [164]:
Z = np.arange('2021-07', '2021-08', dtype='datetime64[D]')
print(Z)

['2021-07-01' '2021-07-02' '2021-07-03' '2021-07-04' '2021-07-05'
 '2021-07-06' '2021-07-07' '2021-07-08' '2021-07-09' '2021-07-10'
 '2021-07-11' '2021-07-12' '2021-07-13' '2021-07-14' '2021-07-15'
 '2021-07-16' '2021-07-17' '2021-07-18' '2021-07-19' '2021-07-20'
 '2021-07-21' '2021-07-22' '2021-07-23' '2021-07-24' '2021-07-25'
 '2021-07-26' '2021-07-27' '2021-07-28' '2021-07-29' '2021-07-30'
 '2021-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [173]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)

[1. 1. 1.]
[2. 2. 2.]


In [174]:
np.add(A,B,out=B)

array([3., 3., 3.])

In [168]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [169]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [170]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [182]:
Z = np.random.uniform(0,10,10)
print(Z)

print('\nExtracting methods:')
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[3.09290027 3.32237575 4.13218522 8.86688275 8.79898129 1.22164981
 9.90181699 1.43435741 9.77908824 6.76396197]

Extracting methods:
[3. 3. 4. 8. 8. 1. 9. 1. 9. 6.]
[3. 3. 4. 8. 8. 1. 9. 1. 9. 6.]
[3. 3. 4. 8. 8. 1. 9. 1. 9. 6.]
[3 3 4 8 8 1 9 1 9 6]
[3. 3. 4. 8. 8. 1. 9. 1. 9. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [186]:
print('First way:')
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
print('\nSecond way:')
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

First way:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

Second way:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [193]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [194]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)


In [77]:
Z = np.random.random(10)
print('Bfter Sorting:\n', Z)

print('\nAfter Sorting:')
Z.sort()
print(Z)

Bfter Sorting:
 [0.48563335 0.06776903 0.16660166 0.43446737 0.13841986 0.94303121
 0.60429877 0.02889547 0.03032042 0.56965563]

After Sorting:
[0.02889547 0.03032042 0.06776903 0.13841986 0.16660166 0.43446737
 0.48563335 0.56965563 0.60429877 0.94303121]


#### 41. How to sum a small array faster than np.sum? (★★☆)


In [203]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)


In [211]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 0 0 1]
[1 1 0 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)


In [215]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [76]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.35808868 0.88099145 0.90281289 0.75879128 0.7752662  0.73143263
 0.62568046 0.27023511 1.2162435  1.10105759]
[1.11253004 1.0151503  0.70581324 1.30140112 1.43498768 0.9622905
 1.17637869 1.25046606 0.65910117 1.12013703]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [74]:
Z = np.random.random(10)
print('Before replacing:\n', Z)

print('\nAfter replacing:')
Z[Z.argmax()] = 0
print(Z)

Before replacing:
 [0.57222572 0.63185032 0.95718576 0.13778883 0.23449811 0.64292415
 0.27406888 0.77609588 0.67025139 0.47974217]

After replacing:
[0.57222572 0.63185032 0.         0.13778883 0.23449811 0.64292415
 0.27406888 0.77609588 0.67025139 0.47974217]


#### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)


In [226]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


In [230]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [233]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)


In [236]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((20,20))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [252]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)

index = (np.abs(Z-v)).argmin()
print(Z[index])

42.499549358856534
42


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


In [7]:
import warnings
warnings.filterwarnings('ignore')

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [11]:
print('First way:')
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
print('\nSecond way:')
import scipy
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

First way:
[[0.         0.26158256 0.46783049 0.51522336 0.41393065 0.19321942
  0.39571203 0.5846312  0.64347108 0.50249598]
 [0.26158256 0.         0.21108493 0.75933632 0.66775326 0.45175064
  0.3630219  0.5321012  0.89884293 0.40919365]
 [0.46783049 0.21108493 0.         0.97041019 0.87808606 0.65207808
  0.40953891 0.63167595 1.10900673 0.49804324]
 [0.51522336 0.75933632 0.97041019 0.         0.11976505 0.38540453
  0.86356941 0.77090292 0.16894723 0.77930784]
 [0.41393065 0.66775326 0.87808606 0.11976505 0.         0.2682742
  0.74699802 0.75473021 0.23115286 0.74263806]
 [0.19321942 0.45175064 0.65207808 0.38540453 0.2682742  0.
  0.47872614 0.71984543 0.48203832 0.66086046]
 [0.39571203 0.3630219  0.40953891 0.86356941 0.74699802 0.47872614
  0.         0.88745317 0.9532438  0.76993679]
 [0.5846312  0.5321012  0.63167595 0.77090292 0.75473021 0.71984543
  0.88745317 0.         0.93967198 0.13370649]
 [0.64347108 0.89884293 1.10900673 0.16894723 0.23115286 0.48203832
  0.953243

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [73]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print('Before converting:\n', Z.dtype)
print('\nAfter converting:\n', Y.dtype)

Before converting:
 float32

After converting:
 int32


#### 54. How to read the following file? (★★☆)

1, 2, 3, 4, 5

6,  ,  , 7, 8

 ,  , 9,10,11


In [27]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [30]:
print('First way:')
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

print('\nSecond way:')
for index in np.ndindex(Z.shape):
    print(index, Z[index])

First way:
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

Second way:
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)


In [31]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)


In [33]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)


In [37]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.42219505  0.31358628 -0.4509287   0.03766048  0.3007831  -0.02766645
   0.01154377 -0.0662711  -0.17591038  0.47939805]
 [-0.35676504  0.41391414  0.07722584  0.17033135  0.1615915  -0.4519639
   0.11576979  0.31534344 -0.18017739 -0.26526972]
 [-0.54356494 -0.25138107  0.42565789  0.40445251  0.34933088  0.37113756
  -0.51175307  0.197496   -0.15134241 -0.29003336]
 [ 0.26712277  0.40155215 -0.06111416 -0.09544869 -0.54597052  0.13859034
   0.28212785  0.27854878 -0.51669222 -0.14871631]
 [-0.02539645 -0.01877515 -0.23749306 -0.29176308 -0.16329338 -0.0653741
   0.38746554 -0.08486495 -0.01543515  0.51492979]]


#### 59. How to sort an array by the nth column? (★★☆)


In [72]:
Z = np.random.randint(0,10,(3,3))
print('Before sorting:\n', Z)
print('\nAfter sorting:\n', Z[Z[:,1].argsort()])

Before sorting:
 [[2 7 6]
 [1 0 8]
 [6 1 0]]

After sorting:
 [[1 0 8]
 [6 1 0]
 [2 7 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)


In [47]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)


In [70]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print('\nNearst value of 0.5 in the array is:\n', m)


[0.68713823 0.7672633  0.25645265 0.40541684 0.26285915 0.87308849
 0.62864032 0.74433229 0.40078954 0.53972669]

Nearst value of 0.5 in the array is:
 0.5397266926353257


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [78]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
print('Array A:\n', A)
print('\nArray B:\n', B)
print('\n')
for x,y,z in it: z[...] = x + y
print(it.operands[2])

Array A:
 [[0]
 [1]
 [2]]

Array B:
 [[0 1 2]]


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)


In [87]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(f'Name of the array: {Z.name}') #Formatting way
print('Values of the array: {}'.format(Z)) #Another formatting way

Name of the array: range_10
Values of the array: [0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [111]:
print('First way:')
Z = np.ones(10)
print('Z: ', Z)
I = np.random.randint(0,len(Z),20)
print('I: ', I)
Z += np.bincount(I, minlength=len(Z))
print('Z: ', Z)
#To explain how this works, checking the values in 'I', the value 0 existed once, therefore we increment the value in
#the 0's index in 'Z' by 1 which makes it 1+1=2, but if we checked 'I' again, the value 2 existed 4 times, therefore we
#increment the value in the 2's index in 'Z' by 1 four times which makes it 1+1+1+1+1=5  

#Another solution
print('\nSecond way:')
Z = np.ones(10)
print('Z: ', Z)
I = np.random.randint(0,len(Z),20)
print('I: ', I)
np.add.at(Z, I, 1)
print('Z: ', Z)

First way:
Z:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
I:  [4 2 3 5 8 7 5 7 2 3 9 3 6 1 0 9 3 2 9 2]
Z:  [2. 2. 5. 5. 2. 3. 2. 3. 2. 4.]

Second way:
Z:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
I:  [4 4 8 6 6 7 7 4 7 4 9 5 0 8 4 6 8 6 4 6]
Z:  [2. 1. 1. 1. 7. 2. 6. 4. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [112]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#To explain how this works, the values in 'I' represents the indexes and the values in 'X' represents the values of 
#a new array 'array F', for example 'I' doesn't have the values 0,2,5,6,7,8 therefore these indexes in the array F 
#will become 0, but it has value 3 in the indexes 1 and 3 so we take the values of these indexes in array X and sum 
#them in the index 3 of array F 

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [114]:
print('First way:')
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
print('\nSecond way:')
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


First way:
64

Second way:
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [116]:
print('First way:')
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
print('\nSecond way:')
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

First way:
[[65 49 60 58]
 [50 74 42 54]
 [51 62 42 61]]

Second way:
[[65 49 60 58]
 [50 74 42 54]
 [51 62 42 61]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


In [117]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.50894477 0.4989866  0.50373317 0.42066466 0.51515917 0.54444314
 0.62931772 0.52376243 0.61298501 0.49034245]
0    0.508945
1    0.498987
2    0.503733
3    0.420665
4    0.515159
5    0.544443
6    0.629318
7    0.523762
8    0.612985
9    0.490342
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)


In [64]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

array([1.24934842, 1.17225834, 2.12023423, 1.1901562 , 1.19365655])

In [65]:
# Fast version
np.sum(A * B.T, axis=1)

array([1.24934842, 1.17225834, 2.12023423, 1.1901562 , 1.19365655])

In [66]:
# Faster version
np.einsum("ij,ji->i", A, B)

array([1.24934842, 1.17225834, 2.12023423, 1.1901562 , 1.19365655])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [119]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [120]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)


In [121]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


In [122]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  5) ( 0, 43) ( 0, 65) ( 0, 84) ( 1, 34) ( 1, 35) ( 5, 84) ( 6, 49)
 ( 6, 69) ( 6, 82) ( 6, 84) ( 8, 34) ( 8, 62) ( 9, 31) ( 9, 83) (13, 38)
 (13, 53) (31, 83) (32, 67) (32, 68) (32, 70) (32, 81) (34, 35) (34, 62)
 (38, 53) (43, 65) (49, 82) (67, 81) (68, 70) (69, 84)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [127]:
C = np.bincount([1,1,2,3,4,4,6])
print('C: ', C)
A = np.repeat(np.arange(len(C)), C)
print('A: ', A)

C:  [0 2 1 1 2 0 1]
A:  [1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)


In [128]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [137]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [138]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.9722708 , -0.69333163, -0.26201162, -0.48067001, -0.30681084,
       -0.955112  , -0.63637443, -0.6864852 , -0.14252185,  0.78589052,
       -0.19398423,  0.90244937,  0.11046847,  0.10715077, -0.8621756 ,
        0.03416446,  0.97345783, -0.14605897,  0.64017454, -0.58274584,
       -0.4648487 , -0.524849  , -0.6176116 , -0.93294646,  0.65381246,
        0.40379367,  0.75855609,  0.49366973, -0.66932859,  0.53831202,
       -0.39205707,  0.4164446 ,  0.67445775,  0.7363892 , -0.21230088,
       -0.04939595, -0.99136629,  0.68325465,  0.18700872,  0.17238637,
        0.21905464,  0.39423989,  0.57623562,  0.52412927,  0.9491125 ,
       -0.89132561,  0.95011757, -0.01905822, -0.78708595, -0.58737598,
        0.11040058,  0.65410375, -0.69952422, -0.93997905, -0.16612543,
       -0.89943467,  0.79852067,  0.39669071,  0.35159202, -0.03418612,
       -0.13940224,  0.83298892, -0.29245711,  0.55762715,  0.55930479,
       -0.5230103 , -0.40618748, -0.45745816,  0.10266212, -0.50

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [139]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.68465009 8.44145275 3.41195518 0.91580006 2.42589394 2.64278238
 1.46139871 4.0359421  3.84448725 1.54064946]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [140]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.12632723  5.25992532  8.24349491  7.0571351   8.51604688  4.11494262
   0.74680747  6.490641    1.33590607  1.75104669]
 [ 1.01316292 10.83041559  6.2423788   1.87938601  1.54063898 12.73183638
   3.50535038  6.29342211  6.01300253  6.35860396]
 [13.97590929  1.72881131  2.7380437  10.68530753  7.00549471  0.70748942
   3.35042902  0.18068574  7.61133133  1.93966659]
 [15.14663878  3.9634448   8.98780776  2.41754996  6.23501667  5.19518582
  16.38629548  9.98900238  5.95728613 10.41422904]
 [ 3.72846734 15.72092245 10.59838292  3.9419773   3.2421859  15.73032654
   0.04584284 11.12078104 10.21942264  5.86343028]
 [ 7.28554488  3.96290304  3.64868119  2.55349578  5.6802814  11.34062292
  12.8041569   3.57276946  1.49246066 11.75545242]
 [13.69791536  1.74328819  0.1296647   7.99061635  3.34581446  1.4162985
   6.71975319  2.16893306  6.57513202  1.61809485]
 [ 3.07067661 14.97312626  9.27498417  4.24846035  2.14051019 15.76288861
   1.34827043  9.84492195  9.81768466  6.75799728]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)


In [9]:
import warnings
warnings.filterwarnings('ignore')

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print('Z:\n', Z)
print('\nR:\n', R)

Z:
 [[7 4 6 1 6 6 1 4 3 2]
 [7 1 2 8 2 0 6 1 6 9]
 [1 6 6 6 8 4 3 9 0 7]
 [2 0 4 8 2 0 0 2 1 7]
 [9 6 4 4 5 6 3 9 6 5]
 [4 0 9 1 2 3 0 9 7 0]
 [1 1 0 5 1 3 0 3 8 5]
 [8 7 4 9 0 7 3 5 7 4]
 [5 2 1 5 1 5 6 7 7 6]
 [8 7 9 0 7 3 6 4 9 2]]

R:
 [[0 0 0 0 0]
 [0 7 4 6 1]
 [0 7 1 2 8]
 [0 1 6 6 6]
 [0 2 0 4 8]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [11]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)


In [12]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? (★☆☆)


In [16]:
Z = np.random.randint(0,10,50)
print(Z)
print('The most frequent value: ', np.bincount(Z).argmax())

[3 0 0 3 4 9 8 2 0 1 6 2 1 9 1 0 8 5 7 7 5 1 8 5 1 6 9 0 3 8 9 9 7 2 1 1 8
 1 0 2 2 5 3 5 6 7 6 2 1 8]
The most frequent value:  1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [18]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 1 3]
   [1 4 0]
   [1 1 0]]

  [[1 3 3]
   [4 0 3]
   [1 0 4]]

  [[3 3 3]
   [0 3 4]
   [0 4 2]]

  [[3 3 1]
   [3 4 0]
   [4 2 2]]

  [[3 1 0]
   [4 0 0]
   [2 2 2]]

  [[1 0 0]
   [0 0 2]
   [2 2 4]]

  [[0 0 2]
   [0 2 4]
   [2 4 4]]

  [[0 2 1]
   [2 4 0]
   [4 4 0]]]


 [[[1 4 0]
   [1 1 0]
   [3 0 1]]

  [[4 0 3]
   [1 0 4]
   [0 1 0]]

  [[0 3 4]
   [0 4 2]
   [1 0 1]]

  [[3 4 0]
   [4 2 2]
   [0 1 0]]

  [[4 0 0]
   [2 2 2]
   [1 0 1]]

  [[0 0 2]
   [2 2 4]
   [0 1 2]]

  [[0 2 4]
   [2 4 4]
   [1 2 4]]

  [[2 4 0]
   [4 4 0]
   [2 4 4]]]


 [[[1 1 0]
   [3 0 1]
   [2 1 2]]

  [[1 0 4]
   [0 1 0]
   [1 2 3]]

  [[0 4 2]
   [1 0 1]
   [2 3 4]]

  [[4 2 2]
   [0 1 0]
   [3 4 1]]

  [[2 2 2]
   [1 0 1]
   [4 1 2]]

  [[2 2 4]
   [0 1 2]
   [1 2 1]]

  [[2 4 4]
   [1 2 4]
   [2 1 3]]

  [[4 4 0]
   [2 4 4]
   [1 3 2]]]


 [[[3 0 1]
   [2 1 2]
   [0 2 2]]

  [[0 1 0]
   [1 2 3]
   [2 2 0]]

  [[1 0 1]
   [2 3 4]
   [2 0 3]]

  [[0 1 0]
   [3 4 1]
   [0 3 3]]

  [[1 0 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [19]:
# Note: only works for 2d array and value setting using indices
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 13  7 17  6]
 [13  2 10 14  5]
 [ 7 10  2 42  5]
 [17 14 42  3 11]
 [ 6  5  5 11  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [20]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


In [28]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)


In [29]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)


In [31]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print('First way:')
print (Z[np.argsort(Z)[-n:]])

# Fast
print('\nSecond way:')
print (Z[np.argpartition(-Z,n)[:n]])

First way:
[9995 9996 9997 9998 9999]

Second way:
[9997 9999 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


In [32]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)


In [33]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [35]:
x = np.random.rand(int(5e7))

print('First way:')
%timeit np.power(x,3)

print('\nSecond way:')
%timeit x*x*x

print('\nThird way:')
%timeit np.einsum('i,i,i->i',x,x,x)

First way:
1.05 s ± 1.61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Second way:
287 ms ± 9.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Third way:
191 ms ± 1.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


In [36]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [38]:
print('First way:')
Z = np.random.randint(0,5,(10,3))
print(Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
print('\nSecond way:')
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

# soluiton for numerical arrays only, will work for any number of columns in Z
print('\nThird way:')
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

First way:
[[1 0 4]
 [0 2 1]
 [1 2 3]
 [1 1 1]
 [0 3 0]
 [2 1 0]
 [3 3 1]
 [4 1 3]
 [4 0 1]
 [3 0 2]]

Second way:
[[1 0 4]
 [0 2 1]
 [1 2 3]
 [0 3 0]
 [2 1 0]
 [3 3 1]
 [4 1 3]
 [4 0 1]
 [3 0 2]]

Third way:
[[1 0 4]
 [0 2 1]
 [1 2 3]
 [0 3 0]
 [2 1 0]
 [3 3 1]
 [4 1 3]
 [4 0 1]
 [3 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)


In [39]:
print('First way:')
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

print('\nSecond way:')
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

First way:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]

Second way:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)


In [40]:
print('First way:')
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
print('\nSecond way:')
uZ = np.unique(Z, axis=0)
print(uZ)

First way:
[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]

Second way:
[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [50]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print('A and B are defined.')

A and B are defined.


In [51]:
np.einsum('i->', A)       # np.sum(A)

3.904374842143507

In [52]:
np.einsum('i,i->i', A, B) # A * B

array([3.13185403e-01, 5.53191497e-02, 7.34252640e-01, 1.26766639e-01,
       1.91889320e-01, 2.12472460e-01, 9.98274846e-02, 1.79646032e-05,
       1.11788837e-01, 7.38099085e-02])

In [53]:
np.einsum('i,i', A, B)    # np.inner(A, B)

1.9193298055725516

In [54]:
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[3.13185403e-01, 2.54485265e-01, 3.60675955e-01, 6.04909146e-02,
        2.30400432e-01, 4.09300858e-01, 5.83816355e-02, 1.43165389e-01,
        2.43674824e-01, 1.45877511e-01],
       [6.80791880e-02, 5.53191497e-02, 7.84025243e-02, 1.31493113e-02,
        5.00836697e-02, 8.89724419e-02, 1.26908033e-02, 3.11208100e-02,
        5.29692124e-02, 3.17103619e-02],
       [6.37572884e-01, 5.18073009e-01, 7.34252640e-01, 1.23145480e-01,
        4.69041871e-01, 8.33241670e-01, 1.18851477e-01, 2.91451546e-01,
        4.96065457e-01, 2.96972797e-01],
       [6.56321053e-01, 5.33307221e-01, 7.55843729e-01, 1.26766639e-01,
        4.82834297e-01, 8.57743585e-01, 1.22346368e-01, 3.00021833e-01,
        5.10652525e-01, 3.05705440e-01],
       [2.60836898e-01, 2.11948407e-01, 3.00389471e-01, 5.03799423e-02,
        1.91889320e-01, 3.40886789e-01, 4.86232263e-02, 1.19235493e-01,
        2.02944916e-01, 1.21494288e-01],
       [1.62577898e-01, 1.32106027e-01, 1.87230752e-01, 3.14014818e-02,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [58]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print('Vectors X and Y was sampled!')

Vectors X and Y was sampled!


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [59]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)


In [60]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.38291201  0.03305341]
